### ISSUE TITLE
Error handling if gcloud isn't installed

### ISSUE THREAD

**Issue by aman00323** [Naman2706/gcps#1]
- Currently our gcps exit with status code, but we need to display user valid information to set up gcloud if it isn't installed.

- Also the app should exit with having 0 status code.

**Comment by pratikbin** [comment]
This can be the best time to add test cases.

**Comment by aman00323** [comment]
Yes @pratikbin we will be adding testcases and also we are targeting all platforms 


But we need some strategy to releases binaries for different os which people can use directly

**Comment by pratikbin** [comment]
> 
> But we need some strategy to releases binaries for different os which people can use directly
@aman00323  I have a few options for releasing binaries so I'll handle that.

 Let's discuss that on element channel. let me create one. we can integrate this repo with it just like slack
