### ISSUE TITLE
Add Semantic Pull Request 

### ISSUE THREAD

**Issue by aman00323** [Naman2706/gcps#3]
- Add a Semantic Pull Request to maintain flow across people contributions.

**Comment by Naman2706** [comment]
@here Added https://github.com/zeke/semantic-pull-requests. 
Need to check if it's working or not

**Comment by pratikbin** [comment]
Create new PR without sementic commit, and it'll show you like CI failed shows

**Comment by pratikbin** [comment]
Wait, I can't see any CI or semantic commit config file

**Comment by pratikbin** [comment]
Yup it's working, you can close this now @Naman2706 or @aman00323 
![image](https://user-images.githubusercontent.com/68642400/160188295-4748dbae-9a25-4000-b56a-11526c9ae57f.png)

from https://github.com/Naman2706/gcps/pull/7
