### ISSUE TITLE
Add flag to switch quickly between profile

### ISSUE THREAD

**Issue by aman00323** [Naman2706/gcps#6]
- Currently, we are showing a list of profiles when gcp execute, but for better switching, we can provide a flag that can be used easily to switch.

- Current brainstorming is that we will do the following things.
1.  pass flag name like `--name` = `profile name`
2. profile will be matched with gcp config list, if their's a match then it will activate profile.
3. Otherwise it should list profiles that are available.

**Comment by pratikbin** [comment]
I'm also interested into going back to previous/toggle profile with `-` at the end of command like `kubens -` will change to previous namespace, `kubectx` will change to previous context and `gco -` with checkout previous git branch

**Comment by Naman2706** [comment]
Okay, we are going to use the file for that feature and we need to test that for windows. so need to figure that out.
